version: '2'
services:
    web:
      build:
        context: .
        args:
          PGUSER: test_user
          PGPASSWORD: test_password
          PGDATABASE: test_database
          PGHOST: 0.0.0.0
      ports:
        - "5000:5000"
      volumes:
        - .:/code
      depends_on:
        - postgres

    postgres:
      image: postgres:alpine
      environment:
        - POSTGRES_USER=test_user
        - POSTGRES_PASSWORD=test_password
        - POSTGRES_DB=test_database
      volumes:
        - database-data:/var/lib/postgresql/data/
      ports:
        - "5432:5432"

volumes:
  database-data:
